.TH ATLAST 1
.SH NAME
atlast \- John Walker's Forth
.SH SYNOPSIS
.B atlast
[OPTION]... [FILE]...
.SH DESCRIPTION
Run John Walker's Forth, as modified by Mark Carter. Options are D, H, I, R, S, T, ?, U
.SH OPTIONS
.TP
.BR \-I\fIFILE\fR
Include the file and execute it before starting the REPL
.TP
.BR \-U
Print usage and exit. Shows all the options.

