#!/usr/bin/env bash


function print_help {
cat <<EOF
jwf - John Walker's Forth (atlast)
etc
EOF
}
 

case $1 in
    h) print_help ; echo . ; exit ;;
esac

CORE_F=$HOME/repos/cerbo/atlast/core.4th
if [[ -f "$CORE_F" ]]; then
	CORE="-I$CORE_F"
fi

#echo $CORE

rlwrap atlast $CORE $@
