#!/usr/bin/env bash

function print_help {
cat <<EOF
reimport mcacc files
-h this help
EOF
}


function doit {
psql -d beancounter <<EOF
delete from mcacc.xtrans;
\copy  mcacc.xtrans from '/home/mcarter/.mcacc/work/s3/pgposts.csv' delimiter ',';
EOF
}

while getopts "d:h" arg; do
	case $arg in
		h) print_help ; exit 0 ;;
		*) echo "Couldn't understand arg: $arg" ;;
	esac
done


doit
