#!/usr/bin/env bash

function print_help {
cat <<EOF
bean-vacc ACC
view account
-h this help

E.g. bean-vacc hal
EOF
}

ACC=$1

function doit {
psql -d beancounter -c "
select * from  mcacc.vacc('$ACC');
"
}

while getopts "h" arg; do
	case $arg in
		h) print_help ; exit 0 ;;
		*) echo "Couldn't understand arg: $arg" ;;
	esac
done


doit
