#!/usr/bin/env bash

function print_help {
cat <<EOF
bbf - barebones forth
etc
EOF
}
 

case $1 in
    h) print_help ; echo . ; exit ;;
esac

#PATH=.:$PATH
FTH=`which forth`
XDIR=`dirname $FTH`
#rlwrap $FTH

#cat $XDIR/extras.4th <(rlwrap cat) | forth
rlwrap $FTH
