#!/usr/bin/env bash

function print_help {
cat <<EOF
-h this help
-r rectify stock prices
EOF
}
/home/mcarter/repos/cerbo/beancounter

rectify-bean-stockprices.sql

function rsp {
	psql beancounter /home/mcarter/repos/cerbo/beancounter/rectify-bean-stockprices.sql
}

while getopts "hr" arg; do
	case $arg in
		h) print_help ; exit 0 ;;
		r) rsp ;;
		*) echo "Couldn't understand arg: $arg" ;;
	esac
done



