.TH "firefox" "5" "0.0.0" "Mark Carter" "Firefox configuration"
.SH "NAME"
.LP 
\fBfirefox\fR \- Mark's configuration options
.SH "DESCRIPTION"
.LP 
You can edit options in firefox by pointing your browser to
\fBabout:config\fR.
.SH "PARAMETERS"
.LP 
\fBimage.animation_mode;none\fR \- Turn off GIF animation
.br 


\fBDate\fR \- Date of some moment
.br 
\fBLocation\fR \- Location of someplace
.br 
.TP 
\fBName\fR = \fIname\fR
Specifies the name of something.
.TP 
\fBDate\fR = \fIy/m/d\fR
Specifies the date of some moment, in notation
year/month/date separated by / characters.
.TP 
\fBLocation\fR = \fIplace\fR
Specifies the place of somewhere, this should
be a known and defined place which the program
can understand.
.SH "FILES"
.LP 
/etc/myconfig
/usr/share/<PROG>/etc/myconfig
.SH "SEE ALSO"
.LP 
myprogram(2) myotherprogram(2)
