.TH "truecrypt" "1" "24-Nov-2008" "Mark Carter" "mcarter"
.SH "NAME"
.LP 
truecrypt \- Mark Carter's description of truecrypt
.SH "SYNTAX"
.LP 
myprogram [\fIoption\fP] <\fIfilename\fP>
.br 
myprogram \fI\-dscan\fP <\fIdirectory\fP>
.SH "DESCRIPTION"
.LP 
Mount and unmount encrypted volumes
.SH "OPTIONS"
.LP 
.TP 
\fB\-d\fR <\fIdirectory\fP>
Unmounts <\fIdirectory\fP>.
.TP 
\fB\-\-mount\fR <\fIvolume\fP> <\fIdirectory\fP>
Mount a <\fIvolume\fP> as <\fIdirectory\fP>.

.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.LP 
truecrypt \-\-mount ~/myfile /media/truecrypt1
.LP 
This mounts the truecrypt file you created MYFILE onto the directory /media/truecrypt1.
.LP 
To dismount a volume:
.LP 
truecrypt \-d /media/truecrypt1
.SH "AUTHORS"
.LP 
Mark Carter <alt.mcarter@googlemail.com>
.LP 
Created: 24\-Nov\-2008
.SH "SEE ALSO"
.LP 
mcarter(1)
