#!/usr/bin/env bash 

source h5utils.sh

SYM=`basename $PWD`
FILE=

function print_help () {
cat << EOF
Download decade worth of data for a share
Sym is based on current working directory unless '-s' option used
Options:
-h this help
-s sym  download for ticker (e.g. VOD.L)
EOF
}

function logging () {
	# deprecated function
	exec > >(tee -a h5mc.log)
	echo "h5get begin `date`"
	set -x
	echo "Symbol to fetch, based on directory name: $SYM"
	set +x
	echo "h5get end"
	echo
}

function sort_file () {
	TMP=`mktemp`
	sort $FILE >$TMP 
	# the sed line moves the header line back from the bottom to the top
	sort $FILE >$TMP
	sed '1h;1d;$!H;$!d;G' $TMP > $FILE
	rm $TMP
}

function do_main() {
	OUTDIR=$HOME/.fortran/tickers/$SYM
	mkdir -p $OUTDIR/out
	FILE=$OUTDIR/raw.dat
	url=$(print_decade_url $SYM)
	curl -s $url > $FILE
	sort_file
}

while getopts "hs:" opt
do
	case $opt in
		h) print_help ; exit 0 ;;
		s) SYM=$OPTARG ;;
		*) echo "Unknown option: $opt" ; exit 0 ;;
	esac
done

do_main
