#!/usr/bin/env bash

# resort raw.dat file

FILE=raw.dat

function print_help () {
cat <<EOF
Sort the raw.dat file
Options:
-f FILE sort specified file, rather than raw.dat in current directory
-h      print this help
EOF
}


while getopts "h" opt
do
	case $opt in
		f) FILE=$OPTAEG ;;
		h) print_help ; exit 0 ;;
		*) echo "Unkown option $opt" ; exit 0 ;;
	esac
done

do_main
