#!/usr/bin/env bash


F1=/tmp/momo-shootout
function phase1 {
	rm -f $F1
	for dname in ~/.fortran/tickers/* 
	do
		echo $dname
		cd $dname
		momo.pl  >>$F1
	done
}

[ 0 == 1 ] && phase1 	

grep WIN $F1| sort | uniq --count | sort -n

grep "RELSCALE HI-T + LO-T" $F1 | grep -v GDN_T | cut -d " " -f 5 | stats
