#!/usr/bin/env bash

echo "ydec: Deprecated. probably use h5get"
exit 0


FILE=raw.dat



function do_main () {
	d0=$(date -d '10 years ago' -I)
	f0=$(dfield $d0 0)

	d1=$(date -I)
	f1=$(dfield $d1 1)

	sym="$1"
	pre="http://ichart.finance.yahoo.com/table.csv?s=$sym&"
	post="&g=d&ignore=.csv"
	url="$pre$f0&$f1$post"

	echo $url


	curl -s $url > $FILE
	h5sort $FILE
	#{if(T=1) { k = print arr[2], T}'
}

